package v1

var links = map[string]string{
	// a
	"angular": "https://angular.io/docs",
	// b
	"bash":      "https://devdocs.io/bash/",
	"bootstrap": "https://getbootstrap.com/docs/4.1/getting-started/introduction/",
	// c
	"c":            "https://docs.microsoft.com/en-us/cpp/?view=msvc-170",
	"c++":          "https://docs.microsoft.com/en-us/cpp/?view=msvc-170",
	"cpp":          "https://docs.microsoft.com/en-us/cpp/?view=msvc-170",
	"c#":           "https://docs.microsoft.com/en-us/dotnet/csharp/",
	"csharp":       "https://docs.microsoft.com/en-us/dotnet/csharp/",
	"clojure":      "https://clojure.org/guides/getting_started",
	"coffeescript": "https://coffeescript.org/",
	// d
	"docker": "https://docs.docker.com/",
	"dotnet": "https://docs.microsoft.com/en-us/dotnet/",
	"drupal": "https://www.drupal.org/documentation",
	// e
	// f
	"f#":      "https://docs.microsoft.com/en-us/dotnet/fsharp/",
	"fsharp":  "https://docs.microsoft.com/en-us/dotnet/fsharp/",
	"flutter": "https://docs.flutter.dev/",
	// g
	"gatsby":    "https://www.gatsbyjs.com/docs/",
	"git":       "https://git-scm.com/doc",
	"ghost":     "https://ghost.org/",
	"ghost-cms": "https://ghost.org/",
	"go":        "https://go.dev/doc/",
	"golang":    "https://go.dev/doc/",
	"graphql":   "https://graphql.org/learn/",
	"gql":       "https://graphql.org/learn/",
	// h
	"haskel": "https://www.haskell.org/documentation/",
	"hugo":   "https://gohugo.io/documentation/",
	// i
	// j
	"javascript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
	"jquery":     "https://api.jquery.com/",
	// k
	"kubernetes": "https://kubernetes.io/",
	"k8s":        "https://kubernetes.io/",
	// l
	"laravel": "https://laravel.com/docs/8.x/installation",
	// m
	"mdn":       "https://developer.mozilla.org/en-US/docs/Web/Guide",
	"oh-my-zsh": "https://ohmyz.sh/",
	// n
	"next":   "https://nextjs.org/docs/getting-started",
	"nextjs": "https://nextjs.org/docs/getting-started",
	// o
	"objc":        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
	"obj-c":       "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
	"objective c": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
	// p
	"purescript": "https://book.purescript.org/",
	"php":        "https://www.php.net/docs.php",
	"python":     "https://docs.python.org/3/",
	// q
	// r
	"react":    "https://reactjs.org/docs/getting-started.html",
	"rescript": "https://rescript-lang.org/",
	"redux":    "https://redux.js.org/",
	"relay":    "https://relay.dev/docs/",
	"remix":    "https://remix.run/docs/en/v1",
	"rust":     "https://doc.rust-lang.org/book/",
	"ruby":     "https://ruby-doc.org/",
	"rails":    "https://guides.rubyonrails.org/",
	// s
	"sanity":            "https://www.sanity.io/docs/getting-started",
	"strapi":            "https://strapi.io/",
	"styled-components": "https://styled-components.com/",
	"swift":             "https://www.swift.org/documentation/#swift-language",
	"swiftui":           "https://developer.apple.com/documentation/swiftui/",
	// t
	"tailwind":    "https://tailwindcss.com/docs/installation",
	"tailwindcss": "https://tailwindcss.com/docs/installation",
	"typescript":  "https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html",
	// u
	// v
	// w
	"wp":        "https://codex.wordpress.org/Main_Page",
	"wordpress": "https://codex.wordpress.org/Main_Page",
	// x
	"xstate": "https://xstate.js.org/docs/",
	// y
	// z
	// #
	".net": "https://docs.microsoft.com/en-us/dotnet/",
}

func Links() map[string]string {
	return links
}
